Repository farribeiro/wscef-docker, pull requests merged in 2020-01, with the labels that each got.

#72 Upgrade to buster and python 3
  .env.dist
  Dockerfile
  docker-compose.yml
  startup.sh
Labels: P3

#73 Note for Wayland
  README.md
Labels: P1, help wanted

#76 Use enviorment variable
  Dockerfile
Labels: good first issue, help wanted

#78 Docker best practices
  .dockerignore
  Dockerfile
Labels: good first issue, help wanted

#75 Set timezone by the HOST
  Dockerfile
  docker-compose.yml
Labels: good first issue, help wanted
